name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: Jimver/cuda-toolkit@master

    - run: cmake --preset release
    - run: cmake --build --preset release
